plot_predict_interaction.caret_ranger <-
function(forest, data, variable1, variable2, grid = 100, 
          main = paste0("Prediction of the forest for different values of ", 
                 paste0(variable1, paste0(" and ", variable2))), time = NULL) 
{
  newdata <- expand.grid(seq(min(data[[variable1]]), max(data[[variable1]]), 
                             length.out = grid), 
                         seq(min(data[[variable2]]), max(data[[variable2]]), 
                            length.out = grid))
  colnames(newdata) <- c(variable1, variable2)
      # for ranger model extracted from caret::train object
  if (as.character(forest$call)[[1]] == "ranger::ranger") { 
    other_vars <- forest$x  # all but outcome
  }
  else if (as.character(forest$call[[2]])[3] == ".") {     
    other_vars <- setdiff(names(data), as.character(forest$call[[2]])[2])
  }
  else {
    other_vars <- labels(terms(as.formula(forest$call[[2]])))
  }
 
  other_vars <- setdiff(other_vars, c(variable1, variable2))
  n <- nrow(data)
  for (i in other_vars) {
    newdata[[i]] <- data[[i]][sample(1:n, nrow(newdata), 
                                     replace = TRUE)]
  }
  if (forest$treetype == "Regression") {
    newdata$prediction <- predict(forest, newdata, type = "response")$predictions
    plot <- ggplot(newdata, aes_string(x = variable1, y = variable2, 
                                       fill = "prediction")) + 
      geom_raster() + 
      theme_bw() + 
      scale_fill_gradient2(midpoint = min(newdata$prediction) + 
                             0.5 * (max(newdata$prediction) - 
                                   min(newdata$prediction)), 
                           low = "blue", high = "red")
  }
  else if (forest$treetype == "Probability estimation") {
    id_vars <- colnames(newdata)
    pred <- predict(forest, newdata)$predictions
    if (ncol(pred) == 2) {
      newdata[, paste0("probability_", colnames(pred)[1])] <- pred[,1] 
    }                                   #changed from -1 to 1 to get positives
    else {
      newdata[, paste0("probability_", colnames(pred))] <- pred
    }
    newdata <- reshape2::melt(newdata, id.vars = id_vars)
    newdata$prediction <- newdata$value
    plot <- ggplot(newdata, aes_string(x = variable1, y = variable2, 
                                       fill = "prediction")) + 
      geom_raster() + 
      theme_bw() + 
      facet_wrap(~variable) + scale_fill_gradient2(midpoint = min(newdata$prediction) + 
                                                     0.5 * (max(newdata$prediction) 
                                                           - min(newdata$prediction)), 
                                                   low = "blue", high = "red")
  }
  else if (forest$treetype == "Classification") {
    stop(
      "Ranger forest for classification needs to be generated by ranger(..., probability = TRUE).")
  }
  else if (forest$treetype == "Survival") {
    pred <- predict(forest, newdata, type = "response")
    if (is.null(time)) {
      time <- pred$unique.death.times[which.min(abs(colMeans(pred$survival, 
                                                             na.rm = TRUE) - 0.5))]
      message(sprintf(
        "Using unique death time %s which is the closest to predicted median survival time.", 
                      time))
    }
    else if (!time %in% pred$unique.death.times) {
      new_time <- pred$unique.death.times[which.min(abs(pred$unique.death.times - 
                                                          time))]
      message(sprintf("Using closest unique death time %s instead of %s.", 
                      new_time, time))
      time <- new_time
    }
    newdata$prediction <- pred$survival[, pred$unique.death.times == 
                                          time, drop = TRUE]
    plot <- ggplot(newdata, aes_string(x = variable1, y = variable2, 
                                       fill = "prediction")) + 
      geom_raster() + 
      theme_bw() + 
      scale_fill_gradient2(midpoint = min(newdata$prediction) + 
                             0.5 * (max(newdata$prediction) - min(newdata$prediction)), 
                           low = "blue", high = "red")
  }
  else {
    stop(sprintf("Ranger forest type '%s' is currently not supported.", 
                 forest$treetype))
  }
  if (!is.null(main)) {
    plot <- plot + ggtitle(main)
  }
  return(plot)
}